# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://192.168.15.88:3306/IspDB?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: bdservice88.557
